### ISSUE TITLE
Why not using a standardized key agreement protocol?

### ISSUE THREAD

**Issue by huypn12** [ntl92bk/MiTransport#1]
If the main concern of the project is for two parties (client & server) to eventually agree on a secret (k & iv), why don't you use a standardized key agreement protocol, such as Diffie-Hellman key exchange?
Furthermore, do you assume that the communication channel is encrypted or not? If the communication channel between the client & server itself is encrypted, then what is the point of having an additional layer of encryption?

**Comment by ntl92bk** [comment]
@huypn12 
The Diffie-Hellman key exchange is still not secure for a Man in the Middle attack. That is reason i add rsa encrypt step for handshake phase :
https://www.geeksforgeeks.org/man-in-the-middle-attack-in-diffie-hellman-key-exchange/

For transports that themselves support TLS like wss, it is not necessary to use MiTransport, but most of Mirror's existing transports do not support it.

**Comment by huypn12** [comment]
The first point seems to be valid. I couldn't think of any flaw so far. There are Authenticated Key Exchange (AKE) protocols [1] that cope with the MitM attack vector; however, these protocols are quite difficult to implement. AKE is also implemented in TLS [2]
The second point is also valid. For an insecure channel, there should be at least one encryption layer.
Good work.
Cite:
[1] https://crypto.stanford.edu/~dabo/cs255/lectures/key-exch.pdf
[2] "The Transport Layer Security (TLS) Protocol Version 1.3", https://archive.ph/3DqOn
