### ISSUE TITLE
Cannot connect on port numbers other than 7777

### ISSUE THREAD

**Issue by jasonpercival** [ntl92bk/MiTransport#2]
MITransport.cs needs to override Client Connect that uses URI

E.g.

        public override void ClientConnect(Uri uri)
        {
            _innerTransport.ClientConnect(uri);
        }

**Comment by ntl92bk** [comment]
Thank you.
I tried calling method StartClient URI instead of using NetworkManager HUD and it failed to connect as you said.
I updated in commit e0e7a8b7e26435ae30905927c22ecf6b3104a40c
